server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/moviebookingapplication
    username: root
    password: HrsPriyaJr@19
    driver-class-name: com.mysql.cj.jdbc.Driver
